#Spring configuracion perfiles
spring:
  profiles:
    active: prod

#Propiedades Hibernate      
  jpa:
    database: SYBASE
    show-sql: false
    hibernate:
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
       
  jackson:
    time-zone: America/Bogota

#Propiedades origen de datos
  datasource:
    jndi-name: jdbc/oreciprocas  

#Propiedades correo
  mail:
    jndi-name: mail/oreciprocas
    
#Configuracion tamaño maximo archivo
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
    

#Configuración de seguridad OAuth
security:
  oauth2:
    resource:
      id: oreciprocas-rest
      
#Configuracion personalizada aplicacion.
oreciprocas:
  config:
    #Roles LDAP que se mapearan con rol FNA_ADMIN (Separados por coma)
    #Certi
    fna-ldap-roles: ORECIPROCAS_ADM_C
    #Prod
    #fna-ldap-roles: ORECIPROCAS_ADM
  upload: 
    #Directorio base para carga de archivos (gestión operaciones)
    base-dir: /aplicaciones/oreciprocas/upload


