ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "fna/centos7"
  config.vm.hostname = "sybtest"
  #config.ssh.insert_key = false
  
  config.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true
  config.vm.network "private_network", type: "dhcp", nic_type: "virtio"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "sybase16box"
    vb.memory = "1024"
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
  end

  config.vm.synced_folder "/Instaladores/FNA/", "/dist" #, mount_options: ["ro"]
  #TODO: Establecer y pasar usuario y contraseña a los scripts
  config.vm.provision "install_sybase", type: "shell", path: "install_sybase1_6.sh"  
  # Para ejecutar un script de creación de base de datos es necesario lanzado por consola el siguiente comando:
  #
  # vagrant provision --provision-with <NOMBRE_SCRIPT_APROVISIONADO>
  # 
  # Por ejemplo el siguiente comando crea la base de datos de Operaciones Reciprocas
  #
  # vagrant provision --provision-with create_db_oreciprocas
  #
  # Para mayor información consultar la pagina de vagrant:
  # www.vagrantup.com
  #    
  config.vm.provision "create_db_oreciprocas", type: "shell", path: "dbs/create_db_oreciprocas.sh", run: "never"
end
