/*****************************************************************************/
/*	Archivo: 02_insert_departamentos.sql                          		     */
/*	Base de datos: oreciprocas										 	     */
/*	Producto: Operaciones Reciprocas										 */
/*	Aplicaciones Impactadas: oreciprocas				    	             */
/*	Diseño: Zamir García         									         */
/*						                                                     */
/*								PREREQUISITOS		                         */
/*	1. 01_oreciprocas_db.sql                                                 */
/*                                                                           */
/*								PROPOSITO									 */
/*	Carga inicial de datos en la tabla ADM_DEPARTAMENTO 					 */
/*  			                                                             */
/*								MODIFICACIONES								 */
/*	FECHA					AUTOR							RAZON			 */
/* 2019-02-05           Zamir García            Construcción de WI_46008     */
/*****************************************************************************/


USE oreciprocas
GO

INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('05','ANTIOQUIA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('08','ATLANTICO')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('11','BOGOTA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('13','BOLIVAR')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('15','BOYACA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('17','CALDAS')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('18','CAQUETA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('19','CAUCA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('20','CESAR')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('23','CORDOBA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('25','CUNDINAMARCA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('27','CHOCO')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('41','HUILA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('44','LA GUAJIRA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('47','MAGDALENA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('50','META')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('52','NARIÑO')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('54','N. DE SANTANDER')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('63','QUINDIO')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('66','RISARALDA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('68','SANTANDER')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('70','SUCRE')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('73','TOLIMA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('76','VALLE DEL CAUCA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('81','ARAUCA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('85','CASANARE')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('86','PUTUMAYO')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('88','SAN ANDRES')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('91','AMAZONAS')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('94','GUAINIA')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('95','GUAVIARE')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('97','VAUPES')
GO
INSERT INTO dbo.ADM_DEPARTAMENTO (CODIGO_DANE, NOMBRE) VALUES ('99','VICHADA')

GO